spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: false