spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  liquibase:
    enabled: false

server:
  port: 8080
  error:
    include-stacktrace: always
  servlet:
    context-path:

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always